language: java
jdk:
  - openjdk6
node_js:
  - 0.8
rvm:
  - 1.9.2
before_install:
  - npm install -g phantomjs
  - npm install -g testacular@v0.5.8
  - gem install sass
  - gem install compass
branches:
  only:
    - master